# This is the apache configuration
# copy it to /etc/apache2/sites-available/ and enable it using
# a2enmod proxy proxy_http
# a2ensite berlin-zaehlt.conf
# a2dissite 000-default.conf
# mkdir -p /srv/www/csv /srv/www/parquet
# chown we-count:www-data /srv/www/*
# systemctl restart apache2

# you might also want to fetch a certificate using
# apt install certbot python3-certbot-apache
# certbot --apache -d example.com

<VirtualHost *:80>
    <Directory /srv/www/>
        Options +Indexes
        IndexOptions FancyIndexing FoldersFirst SuppressDescription NameWidth=*
        AllowOverride None
        Require all granted
    </Directory>

    Alias /csv/ /srv/www/csv/
    <Directory /srv/www/csv/>
        Options +MultiViews
        RemoveType .gz
        AddEncoding gzip .gz
    </Directory>

    Alias /parquet/ /srv/www/parquet/

    ProxyPass /csv/ !
    ProxyPass /parquet/ !
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/

    ProxyPass /goatcounter/ http://127.0.0.1:9090/
    ProxyPassReverse /goatcounter/ http://127.0.0.1:9090/
</VirtualHost>
